### ISSUE TITLE
NPE with new Kotlin IR compiler

### ISSUE THREAD

**Issue by ZakTaccardi** [asarazan/koverage#17]
Using Kotlin 1.5

```kotlin
typealias FeatureName = String

data class Feature(
    val name: FeatureName,
    val default: Boolean
) {
    companion object
}
```

```kotlin
@Test
fun `Koverage cover`() {
    // For data classes
    Koverage.cover(Feature::class)
}
```

```
java.lang.NullPointerException
	at com.company.Feature.hashCode(Feature.kt)
	at net.sarazan.koverage.testers.DataTester.coverHash(DataTester.kt:52)
	at net.sarazan.koverage.testers.DataTester.cover(DataTester.kt:28)
	at net.sarazan.koverage.testers.DataTester$Companion.cover(DataTester.kt:18)
	at net.sarazan.koverage.Koverage.cover(Koverage.kt:23)
	at com.company.FeatureTest.Koverage cover(FeatureTest.kt:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by ZakTaccardi** [comment]
Btw, the fix ended up being:

![Screen Shot 2021-08-10 at 2 13 02 PM](https://user-images.githubusercontent.com/461114/128914226-b7545f03-597d-44e6-9749-4d207bd750a9.png)
